# Robotic hand parameters

# Vizzy's right hand
vizzy:
  name: vizzy_right_hand
  path: models/vizzy_right_hand.urdf
  palm_normal: "0 -1 0"
  finger_joints:
    - r_thumb_phal_1_joint
    - r_ind_phal_1_joint
    - r_med_phal_1_joint
  grasp_configurations:
    cylindrical:
      r_thumb_phal_1_joint: {pre: 0.0, post: 1.570796}
      r_ind_phal_1_joint:   {pre: 0.0, post: 1.570796}
      r_med_phal_1_joint:   {pre: 0.0, post: 1.570796}
  palm_offset: 0.02

# Shadow robotics dexterous (right) hand
shadow:
  name: shadowhand
  path: models/shadowhand.urdf
  palm_normal: "0 1 0"
  finger_joints: [
    rh_FFJ4, rh_FFJ3, rh_FFJ2,
    rh_MFJ4, rh_MFJ3, rh_MFJ2,
    rh_RFJ4, rh_RFJ3, rh_RFJ2,
    rh_LFJ5, rh_LFJ4, rh_LFJ3, rh_LFJ2,
    rh_THJ5, rh_THJ4, rh_THJ3, rh_THJ2]
  grasp_configurations:
    cylindrical:
      rh_FFJ4: {pre: 0.0, post: 1.570796}
      rh_FFJ3: {pre: 0.0, post: 1.570796}
      rh_FFJ2: {pre: 0.0, post: 1.570796}
      rh_MFJ4: {pre: 0.0, post: 1.570796}
      rh_MFJ3: {pre: 0.0, post: 1.570796}
      rh_MFJ2: {pre: 0.0, post: 1.570796}
      rh_RFJ4: {pre: 0.0, post: 1.570796}
      rh_RFJ3: {pre: 0.0, post: 1.570796}
      rh_RFJ2: {pre: 0.0, post: 1.570796}
      rh_LFJ5: {pre: 0.0, post: 0.0}
      rh_LFJ4: {pre: 0.0, post: 1.570796}
      rh_LFJ3: {pre: 0.0, post: 1.570796}
      rh_LFJ2: {pre: 0.0, post: 1.570796}
      rh_THJ5: {pre: 0.0, post: 0.0} # -0.9 -0.9
      rh_THJ4: {pre: 0.0, post: 1.570796}
      rh_THJ3: {pre: 0.0, post: 1.570796}
      rh_THJ2: {pre: 0.0, post: 1.570796}
  palm_offset: 0.03

# Baxter parallel plates gripper
baxter:
  name: baxter_gripper
  path: models/baxter_gripper.urdf
  palm_normal: "0 0 -1" 
  finger_joints:
    - gripper_l_finger_joint
  grasp_configurations:
    pinch:
      gripper_l_finger_joint: {pre: 0.0, post: 1.0}
      gripper_r_finger_joint: {pre: 0.0, post: -1.0}
  palm_offset: 0.035
